"""Deterministic development provider; never presented as real AI."""

import json

from core.ai.provider import AIProvider, ProviderResponse


class MockProvider(AIProvider):
    name = "mock"

    def generate(self, *, system_prompt: str, user_prompt: str) -> ProviderResponse:
        request = json.loads(user_prompt)
        evidence = request.get("evidence", [])
        if request.get("task") == "Answer a document question":
            return ProviderResponse(json.dumps({
                "answer": "DEVELOPMENT MODE: AI provider unavailable. Available evidence is shown below.",
                "citation_ids": [item["evidence_id"] for item in evidence[:3]],
            }), self.name)
        ids = [item["evidence_id"] for item in evidence]
        payload = {
            "summary": "Development mode: document evidence was extracted, but no AI provider is available.",
            "business_model": "Not generated by an AI provider in development mode.",
            "financial_trends": "Not generated by an AI provider in development mode.",
            "key_risks": ["Not generated by an AI provider in development mode."],
            "red_flags": ["Not found in provided document"],
            "management_commentary": "Not generated by an AI provider in development mode.",
            "uncertainty": "AI provider unavailable; review the cited evidence directly.",
            "further_research": ["Further research ke liye ye points verify kiye ja sakte hain."],
            "citations": [
                {
                    "evidence_id": item["evidence_id"],
                    "document": item["document"],
                    "page": item["page"],
                    "evidence": item["text"],
                }
                for item in evidence[:3]
            ] if ids else [],
        }
        return ProviderResponse(json.dumps(payload), self.name)
