[server]
headless = true
enableCORS = true
enableXsrfProtection = true
maxUploadSize = 1

[browser]
gatherUsageStats = false

[theme]
base = "light"
primaryColor = "#1E6BFF"
backgroundColor = "#FFFFFF"
secondaryBackgroundColor = "#F4F7FB"
textColor = "#142033"
